/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msinghi' at '8/1/14 11:29 AM' with Gradle 2.0
 *
 * @author msinghi, @date 8/1/14 11:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
